samplesheet: ".test/config/samples.tsv"

get_genome:
  database: "ncbi"
  assembly: "GCF_000307535.1"
  fasta: Null
  gff: Null
  gff_source_type:
    [
      "RefSeq": "gene",
      "RefSeq": "pseudogene",
      "RefSeq": "CDS",
      "Protein Homology": "CDS",
    ]
