samplesheet: ".test/config/samples.tsv"

get_genome:
  database: "ncbi"
  assembly: "GCF_000307535.1"
  fasta: Null
  gff: Null
  gff_source_type:
    [
      "RefSeq": "gene",
      "RefSeq": "pseudogene",
      "RefSeq": "CDS",
      "Protein Homology": "CDS",
    ]

fastp:
  extra: ""

mapping:
  tool: "bwa_mem2"
  bowtie2:
    index: ""
    extra: ""
  bwa_mem2:
    extra: ""
    sort: "samtools"
    sort_order: "coordinate"
    sort_extra: ""
  samtools_sort:
    extra: "-m 4G"

mapping_stats:
  gffread:
    extra: ""
  rseqc_infer_experiment:
    extra: ""
  rseqc_bam_stat:
    extra: ""